First homework
PredelinaAsya/ML_System_Design pull request #1
Opened 2024-11-27 19:17 UTC by PredelinaAsya

В ветке main находится выполненная первая часть домашнего задания: 

- настроенный конфиг `.pre-commit-config.yaml`;
- в этом конфиге также заданы настройки линтеров и форматеров (в том числе ruff и black);
- в readme содержится краткое описание проекта.

Остальные задания по заполнению дизайн-документа отражены в рамках данного Pull Request.

2024-11-27 19:31 UTC, EmotionEngineer commented
Добавил себя в ревьюеры, буду смотреть

2024-11-27 19:47 UTC, EmotionEngineer requested changes
Я бы предложил в схему добавить описание архитектуры решения: формат датасета, входных данных, выходных данных, описание планируемой модели для реализации.

2024-11-28 11:40 UTC, PredelinaAsya commented
> Я бы предложил в схему добавить описание архитектуры решения: формат датасета, входных данных, выходных данных, описание планируемой модели для реализации.

@EmotionEngineer, добавила на схему информацию о форматах данных и предполагаемых моделях

2024-11-28 12:26 UTC, EmotionEngineer approved these changes

2024-11-28 12:27 UTC, EmotionEngineer commented
@PredelinaAsya Супер, у меня вопросов больше нет. Аппрув.

2024-12-04 08:13 UTC, medphisiker commented
Привет,

отличная работа, мне все очень понравилось)

При прочтении твоего MLSD мне вспомнился момент из лекции о том, что бывает так же полезно пообщаться с экспертами в области той задачи, которую мы автоматизируем.

Хотел предложить:
1.4 Предпосылки решения
Для решения задачи необходимо:
* Собрать описание ключевых моментов на которые обращают внимание тренеры-люди при оценке прогресса в игре в падл теннис (если это возможно).
И с учетом этого
* Сформировать подход к расчёту эффективности игроков для понимания прогресса в тренировках.

А возможно Заказчик, уже собрал все эти данные и предоставил их тебе как исполнителю)

2024-12-04 08:13 UTC, medphisiker approved these changes

2024-12-04 09:00 UTC, PredelinaAsya commented
@medphisiker, спасибо за обратную связь! Подумаю, как собрать описание ключевых моментов по мнению тренеров

2024-12-08 16:13 UTC, eelduck commented
Добавить pyproject.toml и poetry.lock при использовании poetry
Либо requirements.txt при использовании pip
для зависимостей (как минимум ruff и black)

2024-12-14 17:02 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +
Добавила описание сути проекта в качестве вводной части документа

2024-12-14 18:25 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +- **Что будем считать успехом проекта с точки зрения бизнеса**:
Сделала бизнес-цель и критерии успеха более согласованными: указала в качестве успеха довольных работой системы Заказчиков. Скорее всего, вы подразумеваете, что нужно добавить более скоррелированную метрику с точки зрения бизнеса — прирост числа клиентов падел-центра. Но я не считаю это безопасным шагом: на изменение числа клиентов может влиять очень многое. Если Заказчик считает, что данная аналитика поможет ему привлечь новых клиентов, и готов в это вкладываться, прекрасно — поставим бизнес-целью удовлетворённость Заказчика и реализуем систему, которая ему понравится.

С комментариями про real-time согласна: это требование не является необходимым, поэтому убрала его из списка.

2024-12-14 19:15 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +    - в отчёте должна быть интерпретируемая информация об эффективности отдельных игроков: сравнение активности, количество успешных ударов, динамика активности в течение тренировки.
Добавила конкретики в характеристики эффективности: список характеристик уже обсуждала со спортсменом-любителем —  он подтвердил их полезность. Также в процессе согласование разговора с тренером и другими спортсменами. В результате обсуждений финальный список характеристик может быть изменён

2024-12-14 19:20 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +    - обработка в real-time видеопотока с камеры видеонаблюдения над кортом: к концу тренировки должен быть готов отчёт об эффективности;
Убрала требование про real-time и добавила более детализированное объяснение того, что должно быть в отчёте на выходе

2024-12-14 20:08 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +    - обработка в real-time видеопотока с камеры видеонаблюдения над кортом: к концу тренировки должен быть готов отчёт об эффективности;
Как писала выше, согласна с вами про real-time: это требование избыточно, убрала его

2024-12-14 20:08 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +    - возможность одновременной обработки до 5 видеопотоков (несколько тренировок может идти параллельно). В тестовом режиме -- обработка 1 потока.
Согласна, требование real-time избыточно: убрала его

2024-12-14 20:09 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +    - критерии успеха: интерпретируемый и корректный отчёт на выходе системы, работа в real-time;
Поменяла критерий успеха на предложенный вами вариант, также уточнила в тексте, как собирать мнение спортсменов о работе системы

2024-12-14 20:26 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +1. Детекция и трекинг игроков и мяча
Описала в документе, зачем нужно детектировать и отслеживать игроков и мяч

2024-12-14 20:27 UTC, PredelinaAsya commented on docs/ml_system_design_doc.md
> +2. Определение эффективности каждого игрока по времени в движении, по взаимодействию с мячом
Убрала непонятные слова в этом пункте, сослалась на список базовых характеристик эффективности, про который писала выше

2024-12-14 20:39 UTC, PredelinaAsya commented
> Добавить pyproject.toml и poetry.lock при использовании poetry Либо requirements.txt при использовании pip для зависимостей (как минимум ruff и black)

Добавила ruff и black в requirements.txt

2024-12-14 20:39 UTC, PredelinaAsya commented
@eelduck, внесла изменения по вашим комментариям. Посмотрите, пожалуйста

2024-12-16 07:30 UTC, eelduck commented on docs/ml_system_design_doc.md
> +    - критерии успеха: интерпретируемый и корректный отчёт на выходе системы, работа в real-time;
70% удовлетворенности конечно оптимистично на первом этапе, но ладно, главное что измеримо

2024-12-16 07:34 UTC, eelduck approved these changes

2024-12-16 08:25 UTC, merged