Second homework
PredelinaAsya/ML_System_Design pull request #2
Opened 2024-12-28 05:24 UTC by PredelinaAsya

Ноутбук с EDA находится в папке `notebooks`.

Остальные пункты задания выполнены внутри дизайн документа: `docs/ml_system_design_doc.md`.

2025-01-06 12:53 UTC, EmotionEngineer requested changes
У меня вопросов нет, но давай мы немного ноутбук с EDA допилим, чтобы он влезал в рамки просмотра из GitHub. Можно уменьшить кол-во изображений в ноутбуке, либо можно снизить разрешение при выводе в matplotlib. Так будет в разы удобнее.

2025-01-08 10:36 UTC, PredelinaAsya commented
@EmotionEngineer, уменьшила размер ноутбука: теперь он отображается через интерфейс GitHub.

2025-01-09 07:21 UTC, EmotionEngineer approved these changes

2025-01-09 07:22 UTC, EmotionEngineer commented
@PredelinaAsya У меня вопросов больше нет, аппрув

2025-01-12 13:14 UTC, PredelinaAsya commented
@medphisiker, спасибо за полезные ссылки!

Выбранный датасет содержит только детекционную разметку. Единственное, что можно дополнительно извлечь, -- это номера кадров из названий файлов. При этом информации об id-шниках треков нет.

Выбор и оценка качества методов трекинга в текущий момент осуществляется визуальной оценкой на тестовых видео. Также можно будет сравнивать разные подходы, используя количественные метрики (MOTA, HOTA, IDF1), при добавлении новой разметки

2025-01-13 04:59 UTC, medphisiker approved these changes
Понял, благодарю за развернутый ответ.
Больше у меня вопросов нет)

2025-01-18 20:25 UTC, eelduck approved these changes
Спасибо! Отличная работа - 10 баллов , чувствуется глубокое погружение в домен и тесная работа с бизнесом

Хотелось бы 3 этап расписать подробнее, но понимаю, что в рамках ограниченного времени продумать все и сразу тяжело, так что надеюсь когда-нибудь он расширится пускай и вне курса

Оффтопом могу порекомендовать глянуть систему Hawk Eye для тенниса, мб есть описание принципа работы в каком-либо виде

Еще есть такая штука опен сорс https://github.com/ArtLabss/tennis-tracking - тоже можно вдохновиться методами

2025-01-18 20:27 UTC, PredelinaAsya commented
@eelduck, спасибо за обратную связь и ссылки!

2025-01-18 20:29 UTC, merged